#!/bin/bash
# GITHUB Version
#curl -L "https://raw.githubusercontent.com/andistro/app/refs/heads/alpha/andistro_setup" | bash

sleep 2
clear
# Mensagens coloridas antes da barra de progresso



RESET="\e[0m"
BOLD="\e[1m"
FG="\e[97m"
BG_WHITE="\e[47m"   # fundo branco
FG_BLACK="\e[30m"   # texto preto

PT="\e[42m${BOLD}${FG} Olá, aguarde um instante ${RESET}"
EN="\e[44m${BOLD}${FG} Hello, please wait a moment ${RESET}"
#ES="\e[41m${BOLD}${FG} Hola, espere un momento ${RESET}"
#FR="\e[44m${BOLD}${FG} Bonjour, veuillez patienter ${RESET}"
#DE="\e[43m${BOLD}${FG} Hallo, bitte warten ${RESET}"
#IT="\e[42m${BOLD}${FG} Ciao, attendi un momento ${RESET}"

# an
echo -e "${BG_WHITE}${FG_BLACK}  a  ${RESET} ${BG_WHITE}${FG_BLACK}  n  ${RESET}"
echo

# dis
echo -e "${BG_WHITE}${FG_BLACK}  d  ${RESET} ${BG_WHITE}${FG_BLACK}  i  ${RESET} ${BG_WHITE}${FG_BLACK}  s  ${RESET}"
echo

# tro
echo -e "${BG_WHITE}${FG_BLACK}  t  ${RESET} ${BG_WHITE}${FG_BLACK}  r  ${RESET} ${BG_WHITE}${FG_BLACK}  o  ${RESET}"
echo

echo -e "\n\n$PT\n\n$EN\n"

update_progress() {
    current_step=$1
    total_steps=$2

    percent=$((current_step * 100 / total_steps))
    bar_length=30
    filled_length=$((percent * bar_length / 100))
    empty_length=$((bar_length - filled_length))

    filled_bar=$(printf "%${filled_length}s" | tr " " "=")
    empty_bar=$(printf "%${empty_length}s" | tr " " " ")

    printf "\r[%s%s] %3d%%" "$filled_bar" "$empty_bar" "$percent"
}

total_steps=32  # Número total de etapas que você quer monitorar
current_step=0

{
    #1 Atualiza os repositórios
    sleep 1
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #2 Atualiza os repositórios
    pkg update > /dev/null 2>&1
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #3 Instala o bash
    pkg install --no-install-recommends --option=Dpkg::Options::="--force-confnew" bash -y > /dev/null 2>&1
    # Configuration file '/data/data/com.termux/files/usr/etc/bash.bashrc'
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #4 Instala o openssl
    pkg install --no-install-recommends --option=Dpkg::Options::="--force-confnew" openssl -y > /dev/null 2>&1
    # pkg install --no-install-recommends --option Dpkg::Options::="--force-confold " openssl -y > /dev/null 2>&1 este comando sempre instala a configuração nova
    # Configuration file '/data/data/com.termux/files/usr/etc/tls/openssl.cnf'
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #5 Instala o apt
    pkg install --no-install-recommends --option=Dpkg::Options::="--force-confnew" apt -y > /dev/null 2>&1
    # Configuration file '/data/data/com.termux/files/usr/etc/apt/sources.list'
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #6 Atualiza os pacotes
    pkg upgrade -y > /dev/null 2>&1
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #7 Verifica se o termux-exec está instalado
    if ! dpkg -l | grep -qw termux-exec; then
        pkg install --no-install-recommends termux-exec -y > /dev/null 2>&1
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #8 Verifica se o proot está instalado
    if ! dpkg -l | grep -qw proot; then
        pkg install --no-install-recommends proot -y > /dev/null 2>&1
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #9 Verifica se o x11-repo está instalado
    if ! dpkg -l | grep -qw x11-repo; then
        pkg install --no-install-recommends x11-repo -y > /dev/null 2>&1
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #10 Verifica se o termux-x11-nightly está instalado
    if ! dpkg -l | grep -qw termux-x11-nightly; then
        pkg install --no-install-recommends termux-x11-nightly -y > /dev/null 2>&1
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #11 Verifica se o pulseaudio está instalado
    if ! dpkg -l | grep -qw pulseaudio; then
        pkg install --no-install-recommends pulseaudio -y > /dev/null 2>&1
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #12 Verifica se o wget está instalado
    if ! dpkg -l | grep -qw wget; then
        pkg install --no-install-recommends wget -y > /dev/null 2>&1
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #13 Verifica se o dialog está instalado
    if ! dpkg -l | grep -qw dialog; then
        pkg install --no-install-recommends dialog -y > /dev/null 2>&1
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #14 Verifica se o tar está instalado
    if ! dpkg -l | grep -qw tar; then
        pkg install --no-install-recommends tar -y > /dev/null 2>&1
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #15 Verifica se o curl está instalado
    if ! dpkg -l | grep -qw curl; then
        pkg install --no-install-recommends curl -y > /dev/null 2>&1
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #16 Verifica se o unzip está instalado
    if ! dpkg -l | grep -qw unzip; then
        pkg install --no-install-recommends unzip -y > /dev/null 2>&1
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #17 Verifica se o xz-utils está instalado
    if ! dpkg -l | grep -qw xz-utils; then
        pkg install --no-install-recommends xz-utils -y > /dev/null 2>&1
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #18 Verifica se o debootstrap está instalado
    if ! dpkg -l | grep -qw debootstrap; then
        pkg install --no-install-recommends debootstrap -y > /dev/null 2>&1
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #19 Verifica se o dbus está instalado
    if ! dpkg -l | grep -qw dbus; then
        pkg install --no-install-recommends dbus -y > /dev/null 2>&1
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #20 Verifica se o pv está instalado
    if ! dpkg -l | grep -qw pv; then
        pkg install --no-install-recommends pv -y > /dev/null 2>&1
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #21 Verifica se o git está instalado
    if ! dpkg -l | grep -qw git; then
        pkg install --no-install-recommends git -y > /dev/null 2>&1
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #22 Verifica se o inxi está instalado
    if ! dpkg -l | grep -qw inxi; then
        pkg install --no-install-recommends inxi -y > /dev/null 2>&1
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #23 Verifica se o rsync está instalado
    if ! dpkg -l | grep -qw rsync; then
        pkg install --no-install-recommends rsync -y > /dev/null 2>&1
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #24 Verifica se o termux-api está instalado
    if ! dpkg -l | grep -qw termux-api; then
        pkg install --no-install-recommends termux-api -y > /dev/null 2>&1 # necessita do app Termux:API instalado no dispositivo
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #25 Verifica se o android-tools está instalado
    if ! dpkg -l | grep -qw android-tools; then
        pkg install --no-install-recommends android-tools -y > /dev/null 2>&1
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #26 Verifica se o virglrenderer-android está instalado
    if ! dpkg -l | grep -qw virglrenderer-android; then
        pkg install --no-install-recommends virglrenderer-android -y > /dev/null 2>&1
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #27 Verifica se o angle-android está instalado
    if ! dpkg -l | grep -qw angle-android; then
        pkg install --no-install-recommends angle-android -y > /dev/null 2>&1
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #28 Verifica se o vulkan-loader-android está instalado
    if ! dpkg -l | grep -qw vulkan-loader-android; then
        pkg install --no-install-recommends vulkan-loader-android -y > /dev/null 2>&1
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #29 Todo o pacote de instalação
    git clone --depth 1 -b main https://github.com/andistro/installer.git installer-andistro_setup  > /dev/null 2>&1
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #30 Extrai o pacote de instalação
    rm -rf "$HOME/installer-andistro_setup/.git"
    rm -rf "$HOME/installer-andistro_setup/andistro_setup"
    rm -rf "$HOME/installer-andistro_setup/README.md"
    rm -rf "$HOME/installer-andistro_setup/.editconfig"
    rm -rf "$HOME/installer-andistro_setup/.gitignore"
    rm -rf "$HOME/installer-andistro_setup/.gitattributes"
    mv -f "$HOME/installer-andistro_setup/andistro" "$PREFIX/bin/andistro"
    mv -f "$HOME/installer-andistro_setup/termos.sh" "$HOME/termos.sh"
    rsync -a "$HOME/installer-andistro_setup/" "$PREFIX/var/lib/andistro/"
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #31 Mover o Andistro
    chmod +x "$PREFIX/bin/andistro"
    chmod +x "$PREFIX/var/lib/andistro/lib/share/global"
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #32 Verifica se o jq está instalado
    if ! dpkg -l | grep -qw jq; then
        pkg install --no-install-recommends jq -y > /dev/null 2>&1
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1
}

#Remove os arquivos temporários de instalação
rm -rf "$HOME/installer-andistro_setup"
rm -rf "$HOME/andistro_setup"

chmod +x "$HOME/termos.sh"
bash "$HOME/termos.sh"

# Torna executável o script global e chama ele para carregar as variáveis de ambiente globais do Andistro
chmod +x "$PREFIX/var/lib/andistro/lib/share/global"
source "$PREFIX/var/lib/andistro/lib/share/global"

#Configura as teclas extras do Termux
if ! grep -q "^# Andistro Extra keys$" ~/.termux/termux.properties 2>/dev/null; then
  cat << 'EOF' >> ~/.termux/termux.properties


#############################################################################
# Andistro Extra keys
#############################################################################
extra-keys = [['ESC','/','-','HOME','UP','END','PGUP'], \
              ['TAB','CTRL','ALT','LEFT','DOWN','RIGHT','PGDN'], \
              ['DRAWER','DEL','BKSP','PASTE','','KEYBOARD','ENTER']]
    
EOF
fi

# Habilita a opção de permitir que aplicativos externos abram arquivos no Termux
sed -i '/allow-external-apps/s/^# *//' ~/.termux/termux.properties

# Recarrega as configurações do Termux para aplicar as mudanças
termux-reload-settings
termux-reload-settings </dev/tty 


# Solicita permissão de acesso ao armazenamento (necessário para o funcionamento do Andistro)
andistro --setup storage-permission


# Solicita a otmização da bateria (necessário para o funcionamento do Andistro)
andistro --setup battery


# Solicita a permissão de instalação de aplicativos externos (necessário para o funcionamento do Andistro)
andistro --setup install-apps


# Solicita a instalação do Termux:API (necessário para o funcionamento do Andistro)
dialog --no-shadow --title "$label_install Termux:API" \
    --backtitle "$label_warning" \
    --yes-label "$label_install" \
    --no-label "$label_ignore" \
    --yesno "$label_termux_api_desc" \
    20 $dialog_width

dialog_retorno=$?

clear

if [ $dialog_retorno -eq 0 ]; then
    andistro --setup install-termux-api
else
    clear
fi

# Dar as opções de aplicativos VNC para o usuário escolher qual instalar (necessário para o funcionamento do Andistro)
dialog --no-shadow --title "$label_install VNC" \
        --backtitle "$label_warning" \
        --yes-label "$label_install" \
        --no-label "$label_ignore" \
        --yesno "$label_avnc_desc" \
        20 $dialog_width

dialog_retorno=$?
clear

if [ $dialog_retorno -eq 0 ]; then
    andistro --setup install-vnc
else
    clear
fi

# Questiona o atalho de inicialização rápida do Andistro
andistro --setup autoboot


# verifica e instala o gnupg, necessário para a instalação de distribuições via chave GPG
if ! dpkg -l | grep -qw gnupg; then
    pkg install --no-install-recommends gnupg -y > /dev/null 2>&1
fi


# verifica e instala o gnupg, necessário para a instalação de distribuições via chave GPG
if ! dpkg -l | grep -qw coreutils; then
    pkg install --no-install-recommends coreutils -y > /dev/null 2>&1
fi

clear

andistro </dev/tty 